version: '3'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./redis-master.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-net

  redis-replica1:
    image: redis:latest
    container_name: redis-replica1
    ports:
      - "6380:6379"
    volumes:
      - ./redis-replica1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    depends_on:
      - redis-master
    networks:
      - redis-net

  redis-replica2:
    image: redis:latest
    container_name: redis-replica2
    ports:
      - "6381:6379"
    volumes:
      - ./redis-replica2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    depends_on:
      - redis-master
    networks:
      - redis-net

  sentinel1:
    image: redis:latest
    container_name: sentinel1
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica1
      - redis-replica2
    networks:
      - redis-net

  sentinel2:
    image: redis:latest
    container_name: sentinel2
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica1
      - redis-replica2
    networks:
      - redis-net

  sentinel3:
    image: redis:latest
    container_name: sentinel3
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      - redis-master
      - redis-replica1
      - redis-replica2
    networks:
      - redis-net

  monitor:
    build: .
    container_name: redis-monitor
    ports:
      - "5000:5000"
    depends_on:
      - redis-master
      - redis-replica1
      - redis-replica2
      - sentinel1
      - sentinel2
      - sentinel3
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge