version: '3'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"
    volumes:
      - ./redis-master.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - redis-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis-replica1:
    image: redis:latest
    container_name: redis-replica1
    ports:
      - "6380:6379"
    volumes:
      - ./redis-replica1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - redis-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  redis-replica2:
    image: redis:latest
    container_name: redis-replica2
    ports:
      - "6381:6379"
    volumes:
      - ./redis-replica2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - redis-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 3

  sentinel1:
    image: redis:latest
    container_name: sentinel1
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel1.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      redis-master:
        condition: service_healthy
      redis-replica1:
        condition: service_healthy
      redis-replica2:
        condition: service_healthy
    networks:
      - redis-net

  sentinel2:
    image: redis:latest
    container_name: sentinel2
    ports:
      - "26380:26379"
    volumes:
      - ./sentinel2.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      sentinel1:
        condition: service_started
    networks:
      - redis-net

  sentinel3:
    image: redis:latest
    container_name: sentinel3
    ports:
      - "26381:26379"
    volumes:
      - ./sentinel3.conf:/usr/local/etc/redis/sentinel.conf
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    depends_on:
      sentinel1:
        condition: service_started
    networks:
      - redis-net

  monitor:
    build: .
    container_name: redis-monitor
    ports:
      - "5001:5000"
    depends_on:
      redis-master:
        condition: service_healthy
      sentinel1:
        condition: service_started
    networks:
      - redis-net

  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redisinsight
    ports:
      - "8002:8001"
    volumes:
      - redisinsight-data:/db
    depends_on:
      redis-master:
        condition: service_healthy
    networks:
      - redis-net

networks:
  redis-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

volumes:
  redisinsight-data: